# Generated by Django 4.1.2 on 2022-11-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_githuboauth"),
    ]

    operations = [
        migrations.AddField(
            model_name="githuboauth",
            name="username",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
