# Generated by Django 4.1.3 on 2022-11-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_githuboauth_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstatus",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("Free Trial", "Free Trial"),
                    ("Starter", "Starter"),
                    ("X", "X"),
                ],
                default="Free Trial",
                max_length=255,
            ),
        ),
    ]
