# Generated by Django 4.1.3 on 2022-11-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_userstatus_subscription_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="pronouns",
            field=models.CharField(default="", max_length=20),
        ),
    ]
