# Generated by Django 4.1.2 on 2022-10-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0004_socialprofile_preferred_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialprofile",
            name="preferred_day",
            field=models.CharField(
                choices=[
                    ("Sunday", "Sunday"),
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                    ("Any Day", "Any Day"),
                ],
                default="Any Day",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="socialprofile",
            name="preferred_time",
            field=models.CharField(
                choices=[
                    ("6AM - 12PM", "6AM - 12PM"),
                    ("12PM - 4PM", "12PM - 4PM"),
                    ("4PM - 8PM", "4PM - 8PM"),
                    ("8PM - 12AM", "8PM - 12AM"),
                    ("12AM - 6AM", "12AM - 6AM"),
                    ("Anytime", "Anytime"),
                ],
                default="Anytime",
                max_length=20,
            ),
        ),
    ]
