from .base import *


ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1

SESSION_COOKIE_DOMAIN = "api.devclad.com"
SESSION_COOKIE_NAME = "devclad-session"
SESSION_COOKIE_SAMESITE = "Strict"


REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = ["rest_framework.renderers.JSONRenderer"]

SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS")
SECURE_SSL_REDIRECT = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", cast=bool)
# SESSION_COOKIE_AGE = 2 weeks by default
CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", cast=bool)
SECURE_HSTS_PRELOAD = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
